const { PERMISSIONS, ROLES } = require('../constants/permission.constant');

const ROLE_DEFINITIONS = [
  {
    key: ROLES.SUPERADMIN,
    name: 'Super Admin',
    description: 'Toàn quyền cấu hình hệ thống và dữ liệu đa chi nhánh',
    permissions: Object.values(PERMISSIONS),
    scope: 'global',
    isSystem: true,
    isImmutable: true,
  },
  {
    key: ROLES.SYSTEM_ADMIN,
    name: 'System Admin',
    description: 'Quản trị viên hệ thống hiện tại (sẽ được migrate về vai trò động)',
    permissions: [
      PERMISSIONS.GET_USERS,
      PERMISSIONS.MANAGE_USERS,
      PERMISSIONS.MANAGE_BRANCHES,
      PERMISSIONS.GET_BRANCHES,
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.MANAGE_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.MANAGE_PRODUCTS,
      PERMISSIONS.GET_PRODUCT_INVENTORY,
      PERMISSIONS.GET_SUPPLIERS,
      PERMISSIONS.MANAGE_SUPPLIERS,
      PERMISSIONS.MANAGE_PRODUCT_BATCHS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.MANAGE_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.MANAGE_SALES,
      PERMISSIONS.GET_SALES,
      PERMISSIONS.MANAGE_UNITS,
      PERMISSIONS.GET_UNITS,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.ADMIN,
    name: 'Admin',
    description: 'Chủ cửa hàng - quản trị tất cả nghiệp vụ trong phạm vi chi nhánh',
    permissions: [
      PERMISSIONS.GET_USERS,
      PERMISSIONS.MANAGE_USERS,
      PERMISSIONS.MANAGE_BRANCHES,
      PERMISSIONS.GET_BRANCHES,
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.MANAGE_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.MANAGE_PRODUCTS,
      PERMISSIONS.GET_PRODUCT_INVENTORY,
      PERMISSIONS.GET_SUPPLIERS,
      PERMISSIONS.MANAGE_SUPPLIERS,
      PERMISSIONS.MANAGE_PRODUCT_BATCHS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.MANAGE_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.MANAGE_SALES,
      PERMISSIONS.GET_SALES,
      PERMISSIONS.MANAGE_UNITS,
      PERMISSIONS.GET_UNITS,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.USER,
    name: 'User',
    description: 'Người dùng mặc định với quyền giới hạn',
    permissions: [PERMISSIONS.GET_USERS, PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_BRANCHES, PERMISSIONS.GET_BRANCHES],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.WAREHOUSE_STAFF,
    name: 'Warehouse Staff',
    description: 'Nhân viên kho thao tác phiếu xuất/nhập',
    permissions: [
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.GET_SUPPLIERS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.MANAGE_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_UNITS,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.STORE_KEEPER,
    name: 'Store Keeper',
    description: 'Thủ kho giám sát tồn và giao nhận',
    permissions: [
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.MANAGE_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_PRODUCT_INVENTORY,
      PERMISSIONS.GET_UNITS,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.WAREHOUSE_MANAGER,
    name: 'Warehouse Manager',
    description: 'Quản lý kho chịu trách nhiệm điều phối',
    permissions: [
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.MANAGE_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_PRODUCT_INVENTORY,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.PURCHASING_STAFF,
    name: 'Purchasing Staff',
    description: 'Nhân viên thu mua phụ trách nhập hàng',
    permissions: [
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.GET_SUPPLIERS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.SALES_STAFF,
    name: 'Sales Staff',
    description: 'Nhân viên bán hàng',
    permissions: [
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.MANAGE_SALES,
      PERMISSIONS.GET_SALES,
    ],
    scope: 'branch',
    isSystem: true,
  },
  {
    key: ROLES.ACCOUNTANT,
    name: 'Accountant',
    description: 'Kế toán theo dõi doanh thu và tồn kho',
    permissions: [
      PERMISSIONS.GET_WAREHOUSES,
      PERMISSIONS.GET_PRODUCTS,
      PERMISSIONS.GET_PRODUCT_BATCHS,
      PERMISSIONS.GET_INVENTORY_TRANSACTIONS,
      PERMISSIONS.GET_SALES,
      PERMISSIONS.GET_PRODUCT_INVENTORY,
    ],
    scope: 'branch',
    isSystem: true,
  },
];

const roles = ROLE_DEFINITIONS.map((role) => role.key);

module.exports = {
  roles,
  ROLE_DEFINITIONS,
};
